
<!doctype html>

<html lang="es">
	
<head>
		
<title>RedEducacion</title>
<link rel=Stylesheet href="css/movil.css" media='screen and (min-width: 1px) and (max-width: 800px)'>
<link rel=Stylesheet href="css/pcmac.css" media='screen and (min-width: 801px) and (max-width: 4000px)'>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">		
<script type="text/javascript" src="js/jquery.js"></script>
<script type="text/javascript" src="js/codigo.js"></script>
</head>
	<body>
		
<div id="contenedor">
		
	<header>
			
	<a href="index.php"><h1>Titulo</h1></a>
			
	<h2>Subtítulo </h2>
			
</header>
			
<section>
